// Datos de ejemplo de los 8 correos (más sus variantes) para
// emailService.test.mjs y la vista previa. Sólo datos: cada entrada nombra
// su función de render de emailService.js; nada aquí envía correos.
//
// Las fechas llevan mediodía UTC para caer en el mismo día en cualquier zona.

export const EMAIL_SAMPLES = [
  {
    id: "1-membresia-activada",
    render: "renderMembershipActivated",
    opts: {
      to: "cristopher@example.com",
      name: "Cristopher Hernández",
      planName: "8 clases Reformer",
      startDate: "2026-12-01T12:00:00Z",
      endDate: "2026-12-31T12:00:00Z",
      classLimit: 8,
    },
    subject: "Tu membresía en HIVE ya está activa",
    table: ["Plan", "Clases incluidas", "Inicio", "Vencimiento"],
  },
  {
    id: "2-reserva-confirmada",
    render: "renderBookingConfirmed",
    opts: {
      to: "cristopher@example.com",
      name: "Cristopher Hernández",
      className: "Pilates Reformer",
      date: "2026-12-15T12:00:00Z",
      startTime: "07:00",
      instructor: "Ana",
      classesLeft: 2,
      isWaitlist: false,
    },
    subject: "Reserva confirmada — Pilates Reformer",
    table: ["Clase", "Fecha", "Hora", "Coach", "Tu paquete"],
  },
  {
    id: "2b-reserva-lista-de-espera",
    variant: true,
    render: "renderBookingConfirmed",
    opts: {
      to: "cristopher@example.com",
      name: "Cristopher Hernández",
      className: "Pilates Reformer",
      date: "2026-12-15T12:00:00Z",
      startTime: "19:00",
      instructor: "Ana",
      classesLeft: null,
      isWaitlist: true,
    },
    subject: "En lista de espera — Pilates Reformer",
    table: ["Clase", "Fecha", "Hora", "Coach", "Tu paquete"],
  },
  {
    id: "3-reserva-cancelada",
    render: "renderBookingCancelled",
    opts: {
      to: "cristopher@example.com",
      name: "Cristopher Hernández",
      className: "Pilates Mat",
      date: "2026-12-16T12:00:00Z",
      startTime: "11:00",
      creditRestored: true,
      isLate: false,
      classesLeft: 4,
    },
    subject: "Reserva cancelada — Pilates Mat",
    table: ["Clase", "Fecha", "Hora", "Clases restantes"],
  },
  {
    id: "3b-reserva-cancelada-tardia",
    variant: true,
    render: "renderBookingCancelled",
    opts: {
      to: "cristopher@example.com",
      name: "Cristopher Hernández",
      className: "Sculpt",
      date: "2026-12-16T12:00:00Z",
      startTime: "18:00",
      creditRestored: false,
      isLate: true,
      classesLeft: 3,
    },
    subject: "Reserva cancelada — Sculpt",
    table: ["Clase", "Fecha", "Hora", "Clases restantes"],
  },
  {
    id: "4-recordatorio-semanal",
    render: "renderWeeklyReminder",
    opts: {
      to: "cristopher@example.com",
      name: "Cristopher Hernández",
      classesLeft: 2,
      endDate: "2026-12-31T12:00:00Z",
    },
    subject: "Tu semana en HIVE — reserva tus clases",
    table: ["Tu paquete"],
  },
  {
    id: "5-renovacion-ultima-clase",
    render: "renderRenewalReminder",
    opts: {
      to: "cristopher@example.com",
      name: "Cristopher Hernández",
      planName: "4 Sesiones Studio",
      classesLeft: 1,
      endDate: "2026-12-20T12:00:00Z",
      reason: "last_class",
    },
    subject: "Te queda 1 clase — renueva tu membresía",
    table: ["Plan actual", "Clases restantes", "Vencimiento"],
  },
  {
    id: "5b-renovacion-por-vencer",
    variant: true,
    render: "renderRenewalReminder",
    opts: {
      to: "cristopher@example.com",
      name: "Cristopher Hernández",
      planName: "Studio Ilimitado",
      classesLeft: null,
      endDate: "2026-12-18T12:00:00Z",
      reason: "expiring_soon",
    },
    subject: "Tu membresía vence pronto — HIVE",
    table: ["Plan actual", "Vencimiento"],
  },
  {
    id: "6-recuperar-contrasena",
    render: "renderPasswordResetEmail",
    opts: {
      to: "cristopher@example.com",
      name: "Cristopher Hernández",
      token: "muestra-7f3a9c2e",
    },
    subject: "Restablecer tu contraseña — HIVE",
    table: null,
  },
  {
    id: "7-comprobante-rechazado",
    render: "renderOrderRejected",
    opts: {
      to: "cristopher@example.com",
      name: "Cristopher Hernández",
      reason: "El monto de la transferencia no coincide con el paquete.",
    },
    subject: "Comprobante de pago no aprobado — HIVE Pilates Studio",
    table: null,
  },
  {
    id: "8-bienvenida-administradora",
    render: "renderAdminWelcome",
    opts: {
      to: "fernanda.lopez@example.com",
      name: "Fernanda López",
      tempPassword: "Hive-7kP2q9",
    },
    subject: "Tu acceso de administradora — HIVE Pilates Studio",
    table: ["Correo", "Contraseña temporal"],
  },
];
